import Head from 'next/head'
import Image from 'next/image'
import Stripe from 'stripe'

export async function getServerSideProps(context) {
  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY ?? '', 
  {apiVersion: '2020-08-27'})

  const res = await stripe.prices.list({
    limit: 10,
    expand: ['data.product']
  })

  const prices = res.data.filter(price => price.active)

  return {
    props: { prices }
  }
}
export default function Home({prices}) {
  console.log(prices)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
